function [intersection] = linePlaneIntersection(line_direction,line_point,plane_normal,plane_point)

if (plane_normal(1)*line_direction(1) ...
    +plane_normal(2)*line_direction(2) ...
    +plane_normal(3)*line_direction(3))==0
    intersection = [];
    return;
end

t = ((plane_point(1)-line_point(1))*plane_normal(1) ...
    +(plane_point(2)-line_point(2))*plane_normal(2) ...
    +(plane_point(3)-line_point(3))*plane_normal(3)) ...
    /(plane_normal(1)*line_direction(1) ...
    +plane_normal(2)*line_direction(2) ...
    +plane_normal(3)*line_direction(3));

intersection = zeros(1,3);
intersection(1) = line_point(1)+t*line_direction(1);
intersection(2) = line_point(2)+t*line_direction(2);
intersection(3) = line_point(3)+t*line_direction(3);

end